version: "3.7"

services:
  db:
    image: postgres
    restart: always
    env_file:
      - db.env
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    networks:
      - docs_net

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - docs_net

volumes:
  postgres-data:

networks:
  docs_net:
    driver: bridge
